logging:
  level:
    com:
      cloud: DEBUG
  file: Log/myLog.log
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} [%X{CORRELATION_ID}] -%msg%n'
    file: '%d{yyyy-MM-dd HH:mm:ss} [%X{CORRELATION_ID}] [%thread] %-5level %logger{40}-%msg%n'
server:
  port: 8084
  tomcat:
    max-swallow-size: 100MB
spring.profiles: local  
 
spring:
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    username: noreply@loandost.com 
    password: R@ply@N@3168
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
        debug: true
        transport:
          protocol: smtp      
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
